
package cn.sc.webservice.demo.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWSImpl", targetNamespace = "http://api.demo.webservice.sc.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://api.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.api.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://api.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.api.HelloResponse")
    @Action(input = "http://api.demo.webservice.sc.cn/HelloWSImpl/helloRequest", output = "http://api.demo.webservice.sc.cn/HelloWSImpl/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
