
package cn.sc.webservice.demo.cxf.api;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloCXFService", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/", wsdlLocation = "http://localhost:8080/cxf_server?wsdl")
public class HelloCXFService
    extends Service
{

    private final static URL HELLOCXFSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOCXFSERVICE_EXCEPTION;
    private final static QName HELLOCXFSERVICE_QNAME = new QName("http://api.cxf.demo.webservice.sc.cn/", "HelloCXFService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/cxf_server?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOCXFSERVICE_WSDL_LOCATION = url;
        HELLOCXFSERVICE_EXCEPTION = e;
    }

    public HelloCXFService() {
        super(__getWsdlLocation(), HELLOCXFSERVICE_QNAME);
    }

    public HelloCXFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOCXFSERVICE_QNAME, features);
    }

    public HelloCXFService(URL wsdlLocation) {
        super(wsdlLocation, HELLOCXFSERVICE_QNAME);
    }

    public HelloCXFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOCXFSERVICE_QNAME, features);
    }

    public HelloCXFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloCXFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloCXF
     */
    @WebEndpoint(name = "HelloCXFPort")
    public HelloCXF getHelloCXFPort() {
        return super.getPort(new QName("http://api.cxf.demo.webservice.sc.cn/", "HelloCXFPort"), HelloCXF.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloCXF
     */
    @WebEndpoint(name = "HelloCXFPort")
    public HelloCXF getHelloCXFPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://api.cxf.demo.webservice.sc.cn/", "HelloCXFPort"), HelloCXF.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOCXFSERVICE_EXCEPTION!= null) {
            throw HELLOCXFSERVICE_EXCEPTION;
        }
        return HELLOCXFSERVICE_WSDL_LOCATION;
    }

}
