
package cn.sc.webservice.demo.cxf.api;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloCXF", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloCXF {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.cxf.api.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.cxf.api.HelloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns cn.sc.webservice.demo.cxf.api.GetMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getMap", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.cxf.api.GetMap")
    @ResponseWrapper(localName = "getMapResponse", targetNamespace = "http://api.cxf.demo.webservice.sc.cn/", className = "cn.sc.webservice.demo.cxf.api.GetMapResponse")
    public cn.sc.webservice.demo.cxf.api.GetMapResponse.Return getMap();

}
