server:
  context-path: /
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: root
    data-username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
